sudo: required
dist: trusty
language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  global:
   - YARP_BRANCH="master"

before_script:
  #ubuntu dependencies
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo sh -c 'echo "deb http://www.icub.org/ubuntu trusty contrib/science" > /etc/apt/sources.list.d/icub.list'; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --assume-yes --force-yes install cmake libeigen3-dev icub-common libv4lconvert0 libv4l-dev; fi

  # macOS dependencies
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew tap robotology/cask; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install --only-dependencies yarp; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install gsl goocanvas sdl sdl_gfx sdl_image homebrew/science/ipopt; fi
  # Fix for opencv and numpy already installed by system
  - if [ "$TRAVIS_OS_NAME" = osx ]; then rm '/usr/local/bin/f2py'; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then rm -r '/usr/local/lib/python2.7/site-packages/numpy'; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install opencv; fi
  # add QT5 to path so that it can be found by CMake
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export PATH="$PATH:/usr/local/opt/qt/bin"; fi
  #use the same set of cmake options used in the dashboard build
  - source ./admin/scripts/generate-cmake-options.sh
  #install yarp from master
  - git clone --depth 1 -b $YARP_BRANCH https://github.com/robotology/yarp
  - cd yarp
  - mkdir build
  - cd build
  - cmake ../ -DCREATE_GUIS:BOOL=ON -DCREATE_LIB_MATH:BOOL=ON -DCREATE_OPTIONAL_CARRIERS:BOOL=ON -DENABLE_yarpcar_bayer_carrier:BOOL=ON
  - make
  - sudo make install
  - cd ../..
  - mkdir build
  - cd build
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then CMAKE_OPTIONS="${CMAKE_OPTIONS} -DENABLE_icubmod_usbCamera:BOOL=FALSE"; fi
  - cmake ../ ${CMAKE_OPTIONS}

script:

  - cmake --build .
  - sudo make install
  - sudo make uninstall

